# Generated by Django 2.0.5 on 2018-05-09 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tradecore.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ItemStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luxury', models.IntegerField(default=0)),
                ('reputation', models.IntegerField(default=0)),
                ('inventory', models.ForeignKey(default=tradecore.models.Inventory, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tradecore.Inventory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('offered_items', models.ForeignKey(default=tradecore.models.Inventory, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tradecore.Inventory')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_requests', to='tradecore.Profile')),
                ('requested_items', models.ForeignKey(default=tradecore.models.Inventory, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tradecore.Inventory')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_requests', to='tradecore.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='itemstack',
            name='itemtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradecore.ItemType'),
        ),
        migrations.AddField(
            model_name='itemstack',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tradecore.Inventory'),
        ),
        migrations.AddField(
            model_name='factory',
            name='itemtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradecore.ItemType'),
        ),
        migrations.AddField(
            model_name='factory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradecore.Profile'),
        ),
        migrations.AddField(
            model_name='factory',
            name='storage',
            field=models.ForeignKey(default=tradecore.models.Inventory, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tradecore.Inventory'),
        ),
    ]
