# Generated by Django 2.0.5 on 2018-05-27 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradecore', '0002_auto_20180526_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstack',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tradecore.Inventory'),
            preserve_default=False,
        ),
    ]
